/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/ReformedRoom.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ReformedRoom.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.101, 0.078, -2.25]} rotation={[-Math.PI / 2, 0, -2.528]} scale={0.006}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['wire_086086086.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.024']} />
      </group>
      <group position={[9.8, 4.205, 3.397]} rotation={[-Math.PI / 2, 0, -1.565]} scale={2.502}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.boardBack_lambert1_0.geometry} material={materials['lambert1.001']} position={[0, 1.437, -0.009]} scale={[3.743, 1.784, 0.002]} />
          <mesh geometry={nodes.boardEdge_lambert1_0.geometry} material={materials.Material} position={[0, 1.44, 0]} scale={[3.831, 1.846, 0.025]} />
          <mesh geometry={nodes.boardFace_lambert1_0.geometry} material={materials['Material.001']} position={[0, 1.437, -0.004]} scale={[3.702, 1.726, 0.006]} />
          <mesh geometry={nodes.pCube1_lambert1_0.geometry} material={materials['lambert1.001']} position={[0, 0.528, 0.071]} scale={[3.812, 0.007, 0.121]} />
          <mesh geometry={nodes.pCube2_lambert1_0.geometry} material={materials['lambert1.001']} position={[0, 0.533, 0.131]} rotation={[-Math.PI / 2, 0, 0]} scale={[3.812, 0.002, 0.017]} />
        </group>
      </group>
      <group position={[4.791, 6.129, 11.341]} rotation={[-Math.PI / 2, 0, -3.14]} scale={[8.704, 3.976, 6.111]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 0.14, 16.512]}>
            <group position={[0, -0.14, -16.512]}>
              <mesh geometry={nodes.base_Mat_0.geometry} material={materials['Material.004']} position={[0.2, 0, 9.328]} />
            </group>
            <group position={[-58.094, 0.07, 8.256]} rotation={[0, -1.215, 0]}>
              <group position={[19.714, -0.437, -44.372]} rotation={[-0.012, 1.193, 0.083]}>
                <mesh geometry={nodes.L1_Mat_0.geometry} material={materials['material.001']} position={[0.199, -0.013, 9.328]} rotation={[0.022, 0.021, 1.504]} />
              </group>
              <group position={[9.075, 0, 4.298]} rotation={[0, 1.239, 0]} scale={[1.036, 1, 1]}>
                <mesh geometry={nodes.L_Mat_0_1.geometry} material={materials['material.001']} />
                <mesh geometry={nodes.L_Mat_0_2.geometry} material={materials['Material.006']} />
              </group>
            </group>
            <group position={[58.094, 0.07, 8.256]}>
              <group position={[-47.661, -0.437, 2.826]}>
                <mesh geometry={nodes.R1_Mat_0.geometry} material={materials['material.001']} position={[0.2, 0, 9.328]} rotation={[-0.026, -0.001, -1.553]} />
              </group>
              <group position={[0.2, 0, 9.328]}>
                <mesh geometry={nodes.R_Mat_0_1.geometry} material={materials['material.001']} />
                <mesh geometry={nodes.R_Mat_0_2.geometry} material={materials['Material.005']} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.009']} position={[9.41, 5.093, -7.148]} rotation={[0, 1.57, 0]} scale={[3.768, 3.768, 3.308]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <group position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]}>
          <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Cube001_2.geometry} material={materials.metal} />
          <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.026']} />
        </group>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube007.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube010.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube011.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube013.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube014.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube015.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube016.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube017.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube018.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube020.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube021.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube022.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube023.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube024.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube025.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube026.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube027.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube028.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube029.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube030.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube031.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube032.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube033.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube034.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube035.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube036.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube037.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube038.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube039.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube040.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube041.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube042.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube043.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube044.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube045.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube046.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube047.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube048.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube049.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube050.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube051.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube052.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube053.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube054.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube055.geometry} material={materials['Material.013']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <group position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]}>
          <mesh geometry={nodes.Cube061_1.geometry} material={materials['Material.025']} />
          <mesh geometry={nodes.Cube061_2.geometry} material={materials['Material.048']} />
        </group>
        <mesh geometry={nodes.Cube058.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube059.geometry} material={materials['Material.025']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube061.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube062_1.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube063.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube064.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube065_1.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube066.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube067.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube068.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube069.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube070.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube071.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube072.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube073.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube074.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube075.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube076.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube077.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube078.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube079.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube080.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube081.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube082.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube083.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube084.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube085.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube086.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube087.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube088.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube089.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube090.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube091.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube092.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube093.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube094.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube095.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube096.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube097.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube098.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube099.geometry} material={materials.DeskWood} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube100.geometry} material={materials.DeskWood} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube101.geometry} material={materials.DeskWood} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube102.geometry} material={materials.DeskWood} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube103.geometry} material={materials['Material.021']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube104.geometry} material={materials.DeskWood} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube105.geometry} material={materials['Material.019']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube106.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube107.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube108.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube109.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube110.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <group position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]}>
          <mesh geometry={nodes.Cube116_1.geometry} material={materials.MetalBlack} />
          <mesh geometry={nodes.Cube116_2.geometry} material={materials.DeskWood} />
        </group>
        <mesh geometry={nodes.Cube112.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube113.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube114.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube115.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube116.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube117.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube118.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube119.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube120.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube121.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube122.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube123.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube124.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube125.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube126.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube127.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube128.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube129.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube130.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube131.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube132.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube133.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube134.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube135.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube136.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube137.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube138.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube139.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube140.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube141.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube142.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube143.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube144.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube145.geometry} material={materials.MetalBlack} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube146.geometry} material={materials.DeskWood} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube147.geometry} material={materials.DeskWood} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube148.geometry} material={materials.DeskWood} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube149.geometry} material={materials['Material.017']} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
        <mesh geometry={nodes.Cube150.geometry} material={materials.DeskWood} position={[-0.685, -0.083, 0.177]} rotation={[0, -0.898, 0]} />
      </mesh>
      <mesh geometry={nodes['Mid-'].geometry} material={materials['Black-2']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <group position={[-8.252, 2.753, 1.143]} rotation={[-1.56, 0.122, 1.545]} scale={[0.238, 0.212, 0.275]}>
        <mesh geometry={nodes.Circle038.geometry} material={materials['FrameGrey.001']} />
        <mesh geometry={nodes.Circle038_1.geometry} material={materials['Front.001']} />
        <mesh geometry={nodes.Circle038_2.geometry} material={materials['Antennaline.001']} />
        <mesh geometry={nodes.Circle038_3.geometry} material={materials['BackGrey.001']} />
        <mesh geometry={nodes.Circle038_4.geometry} material={materials['Rubber.001']} />
        <mesh geometry={nodes.AntennaLineBottom001.geometry} material={materials['Antennaline.001']} position={[0, -2.676, 0]} />
        <mesh geometry={nodes.AntennaLineTop001.geometry} material={materials['Antennaline.001']} position={[0, 0.018, 0]} />
        <mesh geometry={nodes.AppleLogo001.geometry} material={materials['AppleLogo.001']} position={[0.171, 0.521, -0.079]} />
        <mesh geometry={nodes.BackCameraBottomGreyRing001.geometry} material={materials['BackCaneraGrayRIng.002']} position={[0.702, 0.884, -0.094]} />
        <mesh geometry={nodes.BackCameraBottomLens001.geometry} material={materials['Lens.001']} position={[0.702, 0.884, -0.083]} />
        <mesh geometry={nodes.BackCameraP1001.geometry} material={materials['Black.015']} position={[0.705, 1.027, -0.095]} />
        <mesh geometry={nodes.BackCameraTopGreyRing001.geometry} material={materials['BackCaneraGrayRIng.002']} position={[0.702, 1.178, -0.094]} />
        <mesh geometry={nodes.BackCameraTopLens001.geometry} material={materials['Lens.001']} position={[0.702, 1.178, -0.083]} />
        <mesh geometry={nodes.CameraBump001.geometry} material={materials['Frame.001']} position={[0.704, 1.036, -0.079]} />
        <mesh geometry={nodes.FlashBG001.geometry} material={materials['PinkFlash.002']} position={[0.705, 1.027, -0.093]} />
        <mesh geometry={nodes.FrontCameraContainer001.geometry} material={materials['FrontCameraBlack.002']} position={[0.335, 1.323, 0.08]} />
        <mesh geometry={nodes.FrontSpeakerBG001.geometry} material={materials['FrontSpeaker.001']} position={[0.156, 1.321, 0.077]} />
        <mesh geometry={nodes.iPhoneLogo001.geometry} material={materials['iPhoneLogo.001']} position={[0.2, -1.175, -0.079]} />
        <mesh geometry={nodes.MuteSwitch001.geometry} material={materials['FrameGrey.001']} position={[-0.65, 0.92, 0.009]} />
        <group position={[0.97, 0.562, -0.004]}>
          <mesh geometry={nodes.Circle032.geometry} material={materials['FrameGrey.001']} />
          <mesh geometry={nodes.Circle032_1.geometry} material={materials['Frame.001']} />
        </group>
        <group position={[0.978, -0.043, 0]}>
          <mesh geometry={nodes.Circle031.geometry} material={materials['Black.014']} />
          <mesh geometry={nodes.Circle031_1.geometry} material={materials['FrameGrey.001']} />
        </group>
        <mesh geometry={nodes.SCREEN.geometry} material={materials['Display.002']} />
        <mesh geometry={nodes.VolumeButtons001.geometry} material={materials['FrameGrey.001']} position={[-0.658, 0.208, -0.002]} />
      </group>
      <mesh geometry={nodes.bookA002.geometry} material={materials['Material.051']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials['Material.059']} position={[-7.234, 2.858, -1.176]} rotation={[-2.266, 0.023, 0.406]} scale={[0.244, 0.291, 0.3]} />
      <mesh geometry={nodes.Cup.geometry} material={materials['Material.002']} position={[1.287, 2.606, -8.381]} rotation={[0, -0.474, 0]} scale={[0.386, 0.335, 0.321]} />
      <mesh geometry={nodes['Mid-001'].geometry} material={materials['Black-2']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-002'].geometry} material={materials['Material.028']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-003'].geometry} material={materials['Material.028']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-004'].geometry} material={materials['Material.028']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-005'].geometry} material={materials.Cushion} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-006'].geometry} material={materials.Cushion} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-007'].geometry} material={materials['Black-1']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-008'].geometry} material={materials['Black-1']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-009'].geometry} material={materials['Material.027']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-010'].geometry} material={materials['Material.027']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-011'].geometry} material={materials['Material.027']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-012'].geometry} material={materials['Material.027']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-013'].geometry} material={materials['Material.027']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-014'].geometry} material={materials['Material.027']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-015'].geometry} material={materials['Material.027']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-016'].geometry} material={materials['Material.027']} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-017'].geometry} material={materials.Connector} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes['Mid-018'].geometry} material={materials.Connector} position={[-9.873, 4.943, 1.26]} rotation={[3.121, 1.528, -3.121]} scale={0.568} />
      <mesh geometry={nodes.bookA001.geometry} material={materials['Material.051']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA003.geometry} material={materials['Material.051']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA004.geometry} material={materials['Material.051']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA005.geometry} material={materials['Material.051']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA006.geometry} material={materials['Material.051']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA007.geometry} material={materials['Material.051']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA008.geometry} material={materials['Material.051']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA009.geometry} material={materials['Material.069']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA010.geometry} material={materials['Material.069']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA019.geometry} material={materials['Material.069']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA011.geometry} material={materials['Material.069']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA016.geometry} material={materials['Material.051']} position={[-9.996, 2.98, -4.384]} rotation={[-0.003, 1.158, 3.137]} scale={[4.077, 0.574, 4.264]} />
      <mesh geometry={nodes.bookA017.geometry} material={materials['Material.051']} position={[-9.996, 2.98, -4.384]} rotation={[-0.003, 1.158, 3.137]} scale={[4.077, 0.574, 4.264]} />
      <mesh geometry={nodes.bookA018.geometry} material={materials['Material.069']} position={[-9.996, 2.98, -4.384]} rotation={[-0.003, 1.158, 3.137]} scale={[4.077, 0.574, 4.264]} />
      <mesh geometry={nodes.bookA020.geometry} material={materials['Material.069']} position={[-9.996, 2.98, -4.384]} rotation={[-0.003, 1.158, 3.137]} scale={[4.077, 0.574, 4.264]} />
      <mesh geometry={nodes.bookA021.geometry} material={materials['Material.069']} position={[-9.996, 2.98, -4.384]} rotation={[-0.003, 1.158, 3.137]} scale={[4.077, 0.574, 4.264]} />
      <mesh geometry={nodes.Untitled.geometry} material={materials['wire_086086086.002']} position={[7.924, 0.192, 3.052]} rotation={[Math.PI / 2, 0, 0]} scale={0.052} />
      <mesh geometry={nodes.Box1972.geometry} material={materials['wire_086086086.002']} position={[7.924, 0.192, 3.052]} rotation={[Math.PI / 2, 0, 0]} scale={0.052} />
      <mesh geometry={nodes.Box1973.geometry} material={materials['wire_086086086.002']} position={[7.924, 0.192, 3.052]} rotation={[Math.PI / 2, 0, 0]} scale={0.052} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['wire_086086086.002']} position={[7.924, 0.192, 3.052]} rotation={[Math.PI / 2, 0, 0]} scale={0.052} />
      <group position={[-8.83, 2.659, 3.702]} rotation={[Math.PI / 2, 0, -1.986]} scale={0.007}>
        <mesh geometry={nodes.Rubbish_Bin_By_Berken_obj_1.geometry} material={materials.Mat_1} />
        <mesh geometry={nodes.Rubbish_Bin_By_Berken_obj_2.geometry} material={materials.Mat} />
      </group>
      <group position={[-9.714, 11.79, 6.452]} rotation={[-3.123, 0, 0]} scale={2.932}>
        <mesh geometry={nodes.Stunden_Cube003_1.geometry} material={materials.min_Zeiger} />
        <mesh geometry={nodes.Stunden_Cube003_2.geometry} material={materials['Uhr_2.001']} />
        <mesh geometry={nodes.Stunden_Cube003_3.geometry} material={materials.Uhr_2_NONE} />
        <mesh geometry={nodes.Stunden_Cube003_4.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Stunden_Cube003_5.geometry} material={materials['Material.012']} />
      </group>
      <group position={[-9.976, 14.398, 4.908]} rotation={[-1.571, 0.004, -1.584]} scale={0.122}>
        <mesh geometry={nodes.eb_sconce_light_01_1.geometry} material={materials.blinn3SG} />
        <mesh geometry={nodes.eb_sconce_light_01_2.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.eb_sconce_light_01_3.geometry} material={materials['Material.008']} />
      </group>
      <mesh geometry={nodes.eb_sconce_light_01001.geometry} material={materials.blinn3SG} position={[-9.976, 14.398, 4.908]} rotation={[-1.571, 0.004, -1.584]} scale={0.122} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.010']} position={[-19.877, 11.927, -27.736]} rotation={[-0.018, 0.011, 0.002]} scale={[3.58, 0.058, 1.495]} />
      <group position={[0.1, 2.8, -7.1]} rotation={[Math.PI / 2, 0, 0]} scale={[0.021, 0.015, 0.036]}>
        <mesh geometry={nodes.Mouse_1.geometry} material={materials.aiStandardSurface9SG} />
        <mesh geometry={nodes.Mouse_2.geometry} material={materials.aiStandardSurface6SG} />
        <mesh geometry={nodes.Mouse_3.geometry} material={materials.aiStandardSurface7SG} />
        <mesh geometry={nodes.Mouse_4.geometry} material={materials.aiStandardSurface3SG} />
        <mesh geometry={nodes.Mouse_5.geometry} material={materials.aiStandardSurface2SG} />
        <mesh geometry={nodes.Mouse_6.geometry} material={materials['Keycap material']} />
        <mesh geometry={nodes.Mouse_7.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Mouse_8.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Mouse_9.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Mouse_10.geometry} material={materials['Black rubber']} />
        <mesh geometry={nodes.Mouse_11.geometry} material={materials['Material.023']} />
      </group>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.033']} position={[1.276, 2.934, -8.419]} rotation={[0, -0.498, 0]} scale={[0.223, 0.184, 0.182]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.041']} position={[-4.099, 4.677, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.037']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials['Material.038']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['Material.040']} position={[-4.006, 4.708, -8.816]} rotation={[0.782, -0.085, 0.084]} scale={[0.344, 0.377, 0.373]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.039']} position={[-4.161, 4.708, -8.412]} rotation={[0.779, 0, 0]} scale={[0.374, 0.435, 0.431]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['Material.022']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.022']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.022']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane011.geometry} material={materials['Material.022']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane012.geometry} material={materials['Material.036']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane013.geometry} material={materials['Material.022']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane014.geometry} material={materials['Material.022']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane016.geometry} material={materials['Material.022']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane017.geometry} material={materials['Material.022']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane018.geometry} material={materials['Material.036']} position={[-5.344, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane019.geometry} material={materials['Material.040']} position={[-4.099, 4.708, -8.661]} rotation={[0.779, 0, 0]} scale={[0.418, 0.413, 0.411]} />
      <mesh geometry={nodes.Plane020.geometry} material={materials['Material.040']} position={[-5.313, 4.615, -10.186]} rotation={[0.796, -0.187, 0.188]} scale={[0.478, 0.473, 0.471]} />
      <mesh geometry={nodes.Plane021.geometry} material={materials['Frame.002']} position={[-4.099, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <group position={[-4.099, 4.677, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]}>
        <mesh geometry={nodes.Plane026_1.geometry} material={materials['Frame.002']} />
        <mesh geometry={nodes.Plane026_2.geometry} material={materials['Material.020']} />
      </group>
      <mesh geometry={nodes.Plane023.geometry} material={materials['Frame.002']} position={[-4.099, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane024.geometry} material={materials['Frame.002']} position={[-4.099, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane025.geometry} material={materials['Frame.002']} position={[-4.099, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane026.geometry} material={materials['Frame.002']} position={[-4.099, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane027.geometry} material={materials['Frame.002']} position={[-4.099, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane028.geometry} material={materials['Frame.002']} position={[-4.099, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <group position={[-4.099, 4.677, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]}>
        <mesh geometry={nodes.Plane033_1.geometry} material={materials['Frame.002']} />
        <mesh geometry={nodes.Plane033_2.geometry} material={materials['Material.020']} />
      </group>
      <group position={[-4.099, 4.677, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]}>
        <mesh geometry={nodes.Plane034_1.geometry} material={materials['Frame.002']} />
        <mesh geometry={nodes.Plane034_2.geometry} material={materials['Material.020']} />
      </group>
      <group position={[-4.099, 4.677, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]}>
        <mesh geometry={nodes.Plane035_1.geometry} material={materials.Keyboard} />
        <mesh geometry={nodes.Plane035_2.geometry} material={materials['Material.020']} />
      </group>
      <group position={[-4.099, 4.677, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]}>
        <mesh geometry={nodes.Plane036_1.geometry} material={materials['Frame.003']} />
        <mesh geometry={nodes.Plane036_2.geometry} material={materials['Material.042']} />
      </group>
      <mesh geometry={nodes.Plane033.geometry} material={materials.Screen} position={[-4.099, 4.708, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane034.geometry} material={materials.ScreenGlass} position={[-4.099, 4.677, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane035.geometry} material={materials.ScreenGlass} position={[-4.099, 4.677, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane036.geometry} material={materials.Rubber} position={[-4.099, 4.677, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane037.geometry} material={materials.DisplayGlass} position={[-4.099, 4.677, -8.443]} rotation={[0.779, 0, 0]} scale={[0.512, 0.507, 0.504]} />
      <mesh geometry={nodes.Plane038.geometry} material={materials.material} position={[-5.375, 4.708, -11.026]} rotation={[0.81, -0.247, 0.251]} scale={[0.512, 0.507, 0.504]} />
      <group position={[-2.516, -0.335, 2.518]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-2.574, -0.306, -2.565]}>
        <mesh geometry={nodes.Cube161.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cube161_1.geometry} material={materials['Material.046']} />
      </group>
      <mesh geometry={nodes.Cube060.geometry} material={materials['Material.047']} position={[-0.206, 12.424, -9.691]} rotation={[Math.PI, -1.567, Math.PI]} scale={[0.214, 5.142, 0.337]} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.061']} position={[-6.055, 19.388, -8.998]} rotation={[0, 0, -1.563]} scale={[0.447, 0.263, 0.28]} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.062']} position={[-6.055, 19.388, -8.998]} rotation={[0, 0, -1.563]} scale={[0.447, 0.263, 0.28]} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.060']} position={[-6.055, 19.388, -8.998]} rotation={[0, 0, -1.563]} scale={[0.447, 0.263, 0.28]} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.062']} position={[-6.055, 19.388, -8.998]} rotation={[0, 0, -1.563]} scale={[0.447, 0.263, 0.28]} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Material.068']} position={[-6.055, 19.388, -8.998]} rotation={[0, 0, -1.563]} scale={[0.447, 0.263, 0.28]} />
      <group position={[-11.222, 23.772, -29.517]} scale={[-7.117, -19.423, -25.747]}>
        <mesh geometry={nodes.Landscape_1.geometry} material={materials['Material.044']} />
        <mesh geometry={nodes.Landscape_2.geometry} material={materials['Material.049']} />
      </group>
      <mesh geometry={nodes.bookA013.geometry} material={materials['Material.014']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <mesh geometry={nodes.bookA014.geometry} material={materials['Material.030']} position={[-8.484, 2.949, -3.422]} rotation={[1.236, 1.559, -1.248]} scale={[3.752, 3.571, 3.571]} />
      <group position={[-9.996, 2.98, -4.384]} rotation={[-0.003, 1.158, 3.137]} scale={[4.077, 0.574, 4.264]}>
        <mesh geometry={nodes.Cube166.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Cube166_1.geometry} material={materials['Material.043']} />
      </group>
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[-7.763, 3.196, 0.334]} rotation={[0, 1.563, 0]} scale={0.113} />
      <group position={[-7.809, 3.026, -6.951]} rotation={[0, 0, 1.571]} scale={[0.003, 0.186, 0.186]}>
        <mesh geometry={nodes.Sphere002_1.geometry} material={materials['Material.052']} />
        <mesh geometry={nodes.Sphere002_2.geometry} material={materials['Material.053']} />
      </group>
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.054']} position={[9.448, 8.196, 1.949]} rotation={[1.583, 0, 1.569]} scale={[0.571, 0.586, 0.571]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.055']} position={[0.066, 20, -0.052]} scale={10.075} />
      <group scale={0.01}>
        <mesh geometry={nodes.li_FABRIC_1_FRONT_2263_0030.geometry} material={materials['Material.063']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/ReformedRoom.glb')
